#pragma once

#define LED_CAPS_LOCK_PIN 24
#define LED_PIN_ON_STATE 0
#define SPLIT_LED_STATE_ENABLE

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define RGB_MATRIX_DEFAULT_SPD 120
#define RGB_MATRIX_KEYREACTIVE_ENABLED
#define LED_HITS_TO_REMEMBER 50
#define RGB_DISABLE_WHEN_USB_SUSPENDED
