#pragma once

#define LED_CAPS_LOCK_PIN 24
#define LED_PIN_ON_STATE 0
#define SPLIT_LED_STATE_ENABLE

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_TRANSACTION_IDS_USER SYNC_STATES

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_SPD 120
#undef  RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 192
#define RGB_MATRIX_KEYREACTIVE_ENABLED
#define LED_HITS_TO_REMEMBER 50
